spring.application.name=backend

server.port=8080

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/app_dev
spring.datasource.username=app
spring.datasource.password=app

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=262527053569-uc8h3qjvp44ednvlt277tejd0c0ookjc.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com

# autoriser l?envoi du cookie de session en cross-site
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true

