spring.application.name=backend

server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/wordle}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:wordle}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:wordle}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Security
spring.jpa.open-in-view=false

# JWT
jwt.secret.key=${JWT_SECRET_KEY:your-super-secret-key-change-this-in-production-to-something-long-enough}

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=262527053569-uc8h3qjvp44ednvlt277tejd0c0ookjc.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google