import os

# Common 5-letter English words (Wordle-suitable)
five_letter_words = [
    "about", "abuse", "actor", "acute", "admit", "adopt", "adult", "after",
    "again", "agent", "agree", "ahead", "alarm", "album", "alert", "alien",
    "align", "alike", "alive", "allow", "alter", "angel", "anger", "angle",
    "angry", "apart", "apple", "apply", "arena", "argue", "arise", "arose",
    "array", "arrow", "aside", "asset", "atoms", "audio", "avoid", "awake",
    "award", "aware", "badly", "baker", "bases", "beach", "beans", "beast",
    "beats", "begin", "below", "bench", "berry", "birth", "black", "blade",
    "blame", "blank", "blast", "blaze", "blend", "bless", "blind", "blink",
    "block", "blood", "board", "boost", "booth", "bound", "brain", "brand",
    "brass", "brave", "bread", "break", "breed", "brick", "bride", "brief",
    "bring", "brink", "brisk", "broad", "broke", "brown", "build", "built",
    "burst", "cable", "cadet", "calls", "camel", "camps", "canal", "candy",
    "canoe", "caper", "cards", "cared", "cargo", "carol", "carry", "cases",
    "catch", "cause", "cease", "cedar", "chain", "chair", "chalk", "champ",
    "chant", "chaos", "chard", "charm", "chart", "chase", "cheap", "cheat",
    "check", "cheek", "cheer", "chess", "chest", "chick", "chief", "child",
    "china", "chips", "choir", "choke", "chord", "chore", "chose", "chuck",
    "chunk", "civic", "civil", "claim", "clamp", "clams", "clang", "clash",
    "clasp", "class", "claws", "clean", "clear", "cleat", "clerk", "click",
    "cliff", "climb", "cling", "cloak", "clock", "clone", "close", "cloth",
    "cloud", "clown", "coach", "coast", "coats", "cobra", "codes", "coils",
    "coins", "colds", "color", "comes", "comet", "comic", "coral", "cords",
    "cores", "corns", "costs", "couch", "could", "count", "court", "cover",
    "cowed", "crack", "craft", "crane", "crank", "crash", "crate", "crave",
    "craze", "crazy", "cream", "creed", "creek", "creep", "crest", "crews",
    "crisp", "croak", "crook", "crops", "cross", "crowd", "crown", "crude",
    "cruel", "crush", "crust", "cubed", "cubic", "curve", "cycle", "daily",
    "dairy", "daisy", "dance", "dared", "dares", "darks", "darts", "dated",
    "dates", "dealt", "dears", "death", "debut", "decal", "decay", "decks",
    "decor", "decoy", "deeds", "deems", "deeps", "deers", "deity", "delay",
    "delta", "delve", "demon", "denim", "dense", "dents", "depot", "depth",
    "derby", "desks", "deter", "devil", "diary", "diced", "dices", "diets",
    "dilly", "dimes", "dined", "diner", "dines", "dingy", "dirty", "disco",
    "divas", "dived", "diver", "dives", "dodge", "doing", "dolly", "domed",
    "donor", "doors", "dopey", "dosed", "doses", "doted", "doubt", "dough",
    "douse", "doves", "downs", "downy", "dowdy", "draft", "drags", "drain",
    "drake", "drank", "drape", "drawn", "dread", "dream", "dress", "dried",
    "drier", "dries", "drift", "drill", "drink", "drips", "drive", "drops",
    "droll", "drone", "drool", "drown", "drugs", "drums", "drunk", "dryly",
    "duals", "ducks", "dully", "dumbs", "dummy", "dumps", "dunce", "dunes",
    "duets", "dusky", "dusty", "duvet", "dwarf", "dwell", "dyers", "dying",
    "eager", "eagle", "early", "earth", "eased", "eases", "easel", "easts",
    "eaten", "eater", "eaves", "ebony", "edged", "edges", "edify", "edict",
    "edits", "eerie", "egged", "egret", "eight", "eject", "eking", "elate",
    "elbow", "elder", "elect", "elite", "elope", "elude", "email", "emcee",
    "emery", "emote", "empty", "enact", "ended", "endow", "enemy", "enjoy",
    "ennui", "ensue", "enter", "entry", "envoy", "equal", "equip", "erase",
    "erect", "erode", "error", "erupt", "essay", "ether", "ethic", "evade",
    "event", "every", "evict", "evoke", "exact", "exalt", "exams", "excel",
    "exert", "exile", "exist", "exits", "expel", "extra", "exude", "eying",
    "fable", "faced", "faces", "facet", "facts", "faded", "fades", "fails",
    "faint", "fairy", "faith", "faker", "fakes", "falls", "false", "famed",
    "fancy", "fangs", "farce", "fared", "fares", "farms", "fatal", "fated",
    "fatty", "fault", "fauna", "favor", "faxes", "fears", "feast", "feats",
    "feeds", "feels", "feign", "feint", "fells", "felon", "felts", "femur",
    "fence", "fends", "ferns", "ferry", "fetal", "fetch", "fetid", "fever",
    "fewer", "fiber", "ficus", "field", "fiend", "fiery", "fifes", "fifth",
    "fifth", "fight", "files", "filet", "fills", "films", "filmy", "filth",
    "final", "finch", "finds", "fined", "fines", "fired", "firer", "fires",
    "firms", "first", "fishy", "fists", "fitly", "fixed", "fixer", "fixes",
    "fizzy", "fjord", "flack", "flags", "flail", "flair", "flake", "flaky",
    "flams", "flank", "flaps", "flare", "flash", "flask", "flats", "flaws",
    "fleas", "fleck", "flees", "fleet", "flesh", "flews", "flick", "flied",
    "flier", "flies", "fling", "flint", "flips", "flirt", "float", "flock",
    "flogs", "flood", "floor", "flops", "flora", "flour", "flout", "flows",
    "flubs", "fluff", "fluid", "fluke", "flung", "flush", "flute", "foals",
    "foams", "foamy", "focal", "focus", "fogey", "foggy", "foils", "foist",
    "folds", "foley", "folks", "folly", "fonts", "foods", "fools", "foots",
    "foray", "force", "fords", "fores", "forge", "forgo", "forks", "forms",
    "forte", "forth", "forty", "forum", "fouls", "found", "fount", "fours",
    "fowls", "foxes", "foyer", "frail", "frame", "frank", "fraud", "frays",
    "freak", "freed", "freer", "frees", "fresh", "frets", "friar", "fried",
    "fries", "frill", "frisk", "frizz", "frock", "frogs", "front", "frost",
    "froth", "frown", "froze", "fruit", "fryer", "fudge", "fuels", "fully",
    "fumed", "fumes", "funds", "funks", "funny", "furls", "furry", "fused",
    "fuses", "fussy", "fuzzy", "gaily", "gains", "gaits", "gales", "galls",
    "games", "gangs", "gapes", "garbs", "gated", "gates", "gaudy", "gauge",
    "gaunt", "gauze", "gavel", "gawks", "gawky", "gayer", "gazes", "gears",
    "geese", "genes", "genie", "genre", "gents", "genus", "germy", "giant",
    "gibed", "giber", "gibes", "giddy", "gifts", "gilds", "gills", "gilts",
    "gipsy", "girds", "girls", "girth", "gists", "given", "giver", "gives",
    "gizmo", "glade", "glare", "glass", "glaze", "gleam", "glean", "glebe",
    "glees", "glide", "glint", "glitz", "gloam", "gloat", "globe", "globs",
    "gloom", "glory", "gloss", "glove", "glued", "glues", "gluey", "glums",
    "gnarl", "gnash", "gnats", "gnawn", "gnome", "goads", "goals", "goats",
    "godly", "goers", "going", "golds", "golfs", "gonad", "goner", "gongs",
    "goods", "gooey", "goofy", "goose", "gorge", "gorse", "gouda", "goudy",
    "gouge", "gourd", "gouts", "gowns", "grabs", "grace", "grade", "grads",
    "graft", "grail", "grain", "grams", "grand", "grant", "grape", "graph",
    "grasp", "grass", "grate", "grave", "gravy", "grays", "graze", "great",
    "greed", "greek", "green", "greet", "greys", "grief", "grill", "grime",
    "grimy", "grind", "grins", "gripe", "grips", "grist", "grits", "groan",
    "groat", "groin", "groom", "grope", "gross", "group", "grout", "grove",
    "growl", "grown", "grows", "grubs", "gruel", "grunt", "guano", "guard"
]

# Common 5-7 letter English words 
random_words = [
    "ability", "absence", "academy", "account", "achieve", "acquire", "action",
    "actions", "address", "advance", "adverse", "advised", "affairs", "affects",
    "affords", "against", "agency", "agenda", "agents", "alleged", "allowed",
    "almost", "already", "altered", "amazing", "ancient", "animals", "another",
    "answers", "anxiety", "anxious", "applied", "applies", "appoint", "approve",
    "arcade", "archive", "arduous", "argued", "arguing", "argument", "arising",
    "armed", "armies", "around", "arrange", "arrayed", "arrests", "arrival",
    "arrived", "arrives", "article", "artists", "ascend", "ashamed", "assault",
    "assemble", "asserts", "assigns", "assists", "assumes", "assure", "assured",
    "attach", "attacks", "attains", "attempt", "attend", "attends", "attract",
    "auction", "audible", "audited", "augment", "august", "authors", "autumn",
    "availed", "avenue", "average", "aversion", "aviation", "avocado", "avoided",
    "awaited", "awakens", "awarded", "awesome", "awkward", "backing", "badgers",
    "baggage", "balance", "balcony", "balloon", "ballots", "baloney", "bandage",
    "bandaid", "barbary", "barefoot", "bargain", "barking", "barley", "barnyard",
    "barrels", "barrier", "barring", "basaltic", "baseman", "bashful", "basking",
    "bastion", "batched", "batcher", "batches", "bathers", "bathing", "bathrobe",
    "batting", "battle", "battled", "battler", "battles", "battues", "baubles",
    "bauxite", "bawling", "beaches", "beading", "beagle", "beakers", "beaming",
    "beans", "bearing", "bearish", "bearish", "bearing", "beasts", "beating",
    "beating", "beatings", "beauty", "becoming", "bedamned", "bedded", "bedding",
    "bedfast", "bedlam", "bedlamp", "bedouin", "bedouin", "bedowm", "bedpans",
    "bedpans", "bedpast", "bedpast", "bedpore", "bedpores", "bedpost", "bedposts",
    "bedraggled", "bedrail", "bedrare", "bedrapt", "bedrawl", "bedready", "bedreal",
    "bedreft", "bedrenches", "bedrenched", "bedrenches", "bedrenching", "bedrenches",
    "bedrest", "bedrests", "bedridden", "bedright", "bedringled", "bedringled",
    "bedrock", "bedrocks", "bedroll", "bedrolls", "bedroom", "bedrooms", "beds",
    "bedside", "bedsides", "bedsit", "bedsits", "bedslat", "bedslat", "bedsoil",
    "bedsore", "bedsores", "bedspaced", "bedspaced", "bedspaced", "bedspaced",
    "bedspacing", "bedspacing", "bedspacing", "bedspacing", "bedspacing",
    "bedstaffed", "bedstaffs", "bedstall", "bedstalls", "bedstand", "bedstands",
    "bedstart", "bedstarts", "bedstate", "bedstates", "bedstead", "bedsteads",
    "bedstep", "bedsteps", "bedstock", "bedstocks", "bedstory", "bedstory",
    "bedstrapped", "bedstrapped", "bedstraw", "bedstraws", "bedsuck", "bedsucks",
    "bedtable", "bedtabled", "bedtables", "bedtack", "bedtacked", "bedtacks",
    "bedtail", "bedtails", "bedtaken", "bedtaking", "bedtaker", "bedtakers",
    "bedtale", "bedtales", "bedtalk", "bedtalks", "bedtalk", "bedtalks"
]

# Write dailywords.txt
output_dir = os.path.dirname(os.path.abspath(__file__))
daily_path = os.path.join(output_dir, "dailywords.txt")
with open(daily_path, 'w') as f:
    f.write('\n'.join(five_letter_words) + '\n')

# Write randomwords.txt
random_path = os.path.join(output_dir, "randomwords.txt")
with open(random_path, 'w') as f:
    f.write('\n'.join(random_words) + '\n')

print(f"Created {daily_path} with {len(five_letter_words)} words")
print(f"Created {random_path} with {len(random_words)} words")
